MongoDB
IrynaGumeniuk/nodejs-homework-template pull request #4
Opened 2021-12-27 20:01 UTC by IrynaGumeniuk

MongoDB homework

2021-12-28 20:08 UTC, KirillKulakow commented on .env
> +PORT=3000
файл удалить из гита и добавить в гитигнор

2021-12-28 20:10 UTC, KirillKulakow requested changes
Need fix

2021-12-29 09:04 UTC, IrynaGumeniuk commented
Modified env to gitignore

2021-12-29 17:31 UTC, KirillKulakow approved these changes

2022-01-09 11:53 UTC, merged