Auth part
IrynaGumeniuk/nodejs-homework-template pull request #5
Opened 2022-01-09 12:40 UTC by IrynaGumeniuk

Create auth part

2022-01-10 21:07 UTC, KirillKulakow commented
файл .DS_Store нужен?
удалить и добавить в gitignore

2022-01-10 21:07 UTC, KirillKulakow commented on controllers/auth/index.js
> +  console.log(req.user);
удалить

2022-01-10 21:12 UTC, KirillKulakow requested changes
Need fix

2022-01-10 21:30 UTC, IrynaGumeniuk commented
Вроде исправила) Надеюсь все в порядке

2022-01-12 10:14 UTC, KirillKulakow approved these changes

2022-01-17 11:24 UTC, merged