add avatar loading logic
IrynaGumeniuk/nodejs-homework-template pull request #6
Opened 2022-01-19 12:02 UTC by IrynaGumeniuk

2022-01-19 19:43 UTC, KirillKulakow commented on .env
>  PORT=3000
файл удалить и добавить в гитигнор

2022-01-19 19:51 UTC, KirillKulakow commented on repository/users.js
> +  return await User.findById(id)
смысл всех этих функций с async/await если ты в них возвращаешь асинхронную функцию?

2022-01-19 19:52 UTC, KirillKulakow requested changes
Need fix

2022-01-21 18:08 UTC, IrynaGumeniuk commented
Все исправила, в соотвествии с запросами

2022-01-22 20:40 UTC, KirillKulakow approved these changes

2022-01-25 19:43 UTC, merged